"""
Firestore adapter — drop-in replacement for the Motor MongoDB client.

Exposes a `db` object whose collection accessors implement the subset of
Motor's async API that the Spectr codebase actually uses:

    await db.users.find_one({"email": "..."}, {"_id": 0})
    await db.users.insert_one({...})
    await db.users.update_one({"user_id": "u1"}, {"$set": {...}})
    await db.documents.update_many({"user_id": "u1"}, {"$set": {...}})
    await db.documents.delete_one({"doc_id": "d1", "user_id": "u1"})
    await db.documents.find({"user_id": "u1"}).sort("created_at", -1).limit(20).to_list(20)
    await db.command("ping")

Design choices
--------------
- Every MongoDB "collection" maps 1:1 to a Firestore collection of the same
  name. Document IDs auto-generated by Firestore unless we explicitly set
  them (for immutable-record collections like tos_acceptances we derive the
  doc ID from `acceptance_id`).
- Firestore has no `_id` field. Projections that include `{"_id": 0}` are
  silently accepted and ignored; other projections reduce the returned dict.
- `$or` is rewritten to two sequential queries (Firestore doesn't support
  OR filters across different fields before SDK v2.11; we support it by
  merging results).
- `$set` updates translate to `document.update({})`. Non-existent documents
  auto-create on update to match Mongo upsert-on-update-one semantics we
  rely on in a few places.
- `$regex` is partial — we map to a simple startswith if the pattern looks
  like `^prefix`; anything fancier logs a warning and returns empty.
- `sort()` and `limit()` are chainable like Motor's cursor API.
- `command("ping")` returns `{"ok": 1}` if Firestore is reachable.

If Firebase Admin isn't initialised (no service account), the adapter raises
at import time so the caller can fall back to Mongo or warn.
"""

import os
import re
import logging
import asyncio
import threading
from datetime import datetime, timezone
from typing import Any, Optional

logger = logging.getLogger("firestore_adapter")

# ─── Lazy init ──────────────────────────────────────────────────────────
_firestore_client = None
_init_lock = threading.Lock()


def _init_firestore():
    """Initialise a Firestore client using Firebase Admin credentials.

    Credential sources, in order:
      1. FIRESTORE_SERVICE_ACCOUNT_JSON env var (raw JSON string)
      2. GOOGLE_APPLICATION_CREDENTIALS (path to JSON file)
      3. firebase-admin.json in backend/ (project-local default)
      4. Application Default Credentials (gcloud auth application-default login)
    """
    global _firestore_client
    if _firestore_client is not None:
        return _firestore_client

    with _init_lock:
        if _firestore_client is not None:
            return _firestore_client

        import firebase_admin
        from firebase_admin import credentials, firestore

        if not firebase_admin._apps:
            cred = None

            # 1. Inline JSON string
            raw = os.environ.get("FIRESTORE_SERVICE_ACCOUNT_JSON", "").strip()
            if raw:
                try:
                    import json as _json
                    cred = credentials.Certificate(_json.loads(raw))
                except Exception as e:
                    logger.warning(f"FIRESTORE_SERVICE_ACCOUNT_JSON unusable: {e}")

            # 2. Path in GOOGLE_APPLICATION_CREDENTIALS
            if cred is None:
                path = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "").strip()
                if path and os.path.exists(path):
                    cred = credentials.Certificate(path)

            # 3. Project-local default
            if cred is None:
                here = os.path.dirname(os.path.abspath(__file__))
                local_path = os.path.join(here, "firebase-admin.json")
                if os.path.exists(local_path):
                    cred = credentials.Certificate(local_path)

            # 4. Application Default Credentials
            project_id = os.environ.get("FIREBASE_PROJECT_ID") or "associate-research-services"
            if cred is not None:
                firebase_admin.initialize_app(cred, {"projectId": project_id})
            else:
                try:
                    firebase_admin.initialize_app(
                        credentials.ApplicationDefault(),
                        {"projectId": project_id},
                    )
                except Exception as e:
                    raise RuntimeError(
                        "Firestore unavailable: no service account credentials found. "
                        "Set FIRESTORE_SERVICE_ACCOUNT_JSON, GOOGLE_APPLICATION_CREDENTIALS, "
                        f"or place firebase-admin.json next to server.py. Details: {e}"
                    )

        # If a specific named database was created (instead of the implicit
        # unnamed "(default)" primary), we must pass database_id explicitly.
        # `firebase_admin.firestore.client()` does NOT accept database_id;
        # only the native `google.cloud.firestore.Client` does. We use the
        # native client directly and load credentials from the same service
        # account JSON that firebase_admin already verified.
        database_id = os.environ.get("FIRESTORE_DATABASE_ID", "").strip()

        if database_id:
            from google.cloud import firestore as gcf
            from google.oauth2 import service_account

            # Locate the service account JSON (same resolution order as above)
            sa_path = None
            p_env = os.environ.get("GOOGLE_APPLICATION_CREDENTIALS", "").strip()
            if p_env and os.path.exists(p_env):
                sa_path = p_env
            else:
                here = os.path.dirname(os.path.abspath(__file__))
                local = os.path.join(here, "firebase-admin.json")
                if os.path.exists(local):
                    sa_path = local

            if sa_path:
                creds = service_account.Credentials.from_service_account_file(sa_path)
            else:
                creds = None  # ADC

            project_id = os.environ.get("FIREBASE_PROJECT_ID") or "associate-research-services"
            _firestore_client = gcf.Client(
                project=project_id,
                credentials=creds,
                database=database_id,
            )
            logger.info(f"Firestore client initialised — project={project_id} database={database_id}")
        else:
            _firestore_client = firestore.client()
            logger.info("Firestore client initialised — (default) database")
        return _firestore_client


# ─── Helpers ────────────────────────────────────────────────────────────

_LOOP_EXECUTOR = None

# ─── Quota-error circuit breaker ────────────────────────────────────────
# When Firestore returns 429 (free-tier daily quota blown), the SDK retries
# internally for up to 60 seconds before surfacing the error. Under a live
# demo that means every /assistant/query, every /vault/*, every /history
# hangs for a minute. We detect the first 429 and OPEN a circuit — for the
# next N seconds, every Firestore read/write fails FAST with a sentinel
# "quota-open" RuntimeError, and callers' existing `except Exception` paths
# fall back to in-memory cache / training knowledge / empty responses.
#
# This is what keeps the product responsive during the 24h window between
# a quota blow and the reset (or until billing is enabled).
import time as _time

_QUOTA_OPEN_UNTIL: float = 0.0
_QUOTA_COOLDOWN_S: float = 90.0  # enough that we don't retry every second
_WRITE_TIMEOUT_S: float = 2.5    # fail fast instead of waiting for SDK retry
_READ_TIMEOUT_S: float = 4.0     # reads get a bit more — important queries

class FirestoreQuotaError(RuntimeError):
    """Raised when the circuit is open so callers see 'unavailable' fast."""
    pass


def _is_quota_error(exc: BaseException) -> bool:
    msg = str(exc)
    return ("429" in msg and "Quota" in msg) or "quota metric" in msg.lower()


def _circuit_is_open() -> bool:
    return _time.time() < _QUOTA_OPEN_UNTIL


def _trip_circuit(reason: str = ""):
    global _QUOTA_OPEN_UNTIL
    _QUOTA_OPEN_UNTIL = _time.time() + _QUOTA_COOLDOWN_S
    logger.warning(
        f"firestore_adapter: TRIPPING quota circuit for {_QUOTA_COOLDOWN_S:.0f}s "
        f"({reason[:140] if reason else 'quota exceeded'}). Reads will fail fast; "
        f"caller fallbacks (in-memory cache, training knowledge) will kick in."
    )


async def _run_blocking(fn, *args, **kwargs):
    """Run the sync Firestore call in a thread-pool executor so we don't
    block the event loop. Also implements the quota circuit breaker — once
    tripped, returns fast with FirestoreQuotaError until the cooldown ends.

    Write timeout: 2.5s.  Read timeout: 4s.  If a real network hang exceeds
    these, we assume Firestore is unhealthy and also trip the circuit.
    """
    if _circuit_is_open():
        raise FirestoreQuotaError("firestore quota circuit open")

    loop = asyncio.get_event_loop()
    # Heuristic: writes have no `__name__=='_do_sync'` marker — close enough
    # that we use a single timeout. Individual hot paths (insert_one, find)
    # can override by catching the TimeoutError themselves.
    timeout = _READ_TIMEOUT_S
    try:
        return await asyncio.wait_for(
            loop.run_in_executor(None, lambda: fn(*args, **kwargs)),
            timeout=timeout,
        )
    except asyncio.TimeoutError:
        _trip_circuit(f"timeout after {timeout}s")
        raise FirestoreQuotaError(f"firestore timeout after {timeout}s") from None
    except Exception as e:
        if _is_quota_error(e):
            _trip_circuit(str(e))
            raise FirestoreQuotaError("firestore quota exceeded") from e
        raise


def _drop_id_projection(proj: Optional[dict]) -> Optional[set]:
    """Convert a Mongo projection dict into a set of keys to KEEP.
    Returns None if no projection specified (keep everything)."""
    if not proj:
        return None
    include_keys = {k for k, v in proj.items() if v and k != "_id"}
    if include_keys:
        return include_keys
    # Explicit exclusions (like {"_id": 0}) with no inclusions → keep everything except _id
    return None


def _apply_projection(doc: dict, keep: Optional[set]) -> dict:
    if doc is None:
        return None
    if keep is None:
        out = dict(doc)
        out.pop("_id", None)
        return out
    return {k: doc.get(k) for k in keep if k in doc}


def _apply_where(query, filters: dict):
    """Translate a Mongo-style filter dict into chained .where() calls.
    Supports: equality, $in, $ne, $or, $regex (limited)."""
    from google.cloud.firestore_v1 import FieldFilter

    if not filters:
        return query

    for key, val in filters.items():
        if key == "$or":
            # Firestore doesn't natively support OR across fields pre-v2.11.
            # We return the query unchanged and the caller merges results.
            # Mark it so find/find_one can detect.
            query._spectr_or_clauses = val
            continue

        if key == "$and":
            # $and: [filter1, filter2, ...] — just merge all sub-filters into
            # this query. Firestore ANDs where() clauses by default. If a
            # sub-filter contains $or, the FIRST $or wins (can't combine in FS).
            merged = {}
            nested_or = None
            for sub in (val or []):
                if not isinstance(sub, dict):
                    continue
                if "$or" in sub and nested_or is None:
                    nested_or = sub["$or"]
                    sub = {k: v for k, v in sub.items() if k != "$or"}
                for k, v in sub.items():
                    if k in merged:
                        logger.warning(f"firestore_adapter: $and sub-filter overrides {k!r}; using last value")
                    merged[k] = v
            query = _apply_where(query, merged)
            if nested_or is not None:
                query._spectr_or_clauses = nested_or
            continue

        # Skip any remaining top-level operators we don't handle, rather than
        # sending them to Firestore as field paths (which 400s).
        if key.startswith("$"):
            logger.warning(f"firestore_adapter: top-level operator {key!r} ignored")
            continue

        if isinstance(val, dict):
            if "$in" in val:
                vals = list(val["$in"])[:10]  # Firestore limit
                query = query.where(filter=FieldFilter(key, "in", vals))
            elif "$ne" in val:
                query = query.where(filter=FieldFilter(key, "!=", val["$ne"]))
            elif "$regex" in val:
                pattern = val["$regex"]
                if pattern.startswith("^"):
                    prefix = pattern[1:].rstrip("$")
                    # Firestore trick: >= prefix AND < prefix + \uf8ff
                    query = query.where(filter=FieldFilter(key, ">=", prefix))
                    query = query.where(filter=FieldFilter(key, "<", prefix + "\uf8ff"))
                else:
                    logger.warning(f"firestore_adapter: $regex on '{key}' with non-prefix pattern ignored ({pattern[:60]})")
            elif "$exists" in val:
                # Firestore doesn't have a direct exists; skip
                pass
            elif "$gte" in val:
                query = query.where(filter=FieldFilter(key, ">=", val["$gte"]))
            elif "$lte" in val:
                query = query.where(filter=FieldFilter(key, "<=", val["$lte"]))
            elif "$gt" in val:
                query = query.where(filter=FieldFilter(key, ">", val["$gt"]))
            elif "$lt" in val:
                query = query.where(filter=FieldFilter(key, "<", val["$lt"]))
            else:
                logger.warning(f"firestore_adapter: unsupported operator on '{key}': {list(val.keys())}")
        else:
            query = query.where(filter=FieldFilter(key, "==", val))
    return query


def _apply_update_ops(existing: dict, update_spec: dict) -> dict:
    """Translate a Mongo $set/$inc/$unset update into the new doc state."""
    result = dict(existing or {})
    if "$set" in update_spec:
        for k, v in update_spec["$set"].items():
            result[k] = v
    if "$inc" in update_spec:
        for k, v in update_spec["$inc"].items():
            result[k] = (result.get(k) or 0) + v
    if "$unset" in update_spec:
        for k in update_spec["$unset"].keys():
            result.pop(k, None)
    # Raw field-only update (no operators) — treat as $set
    if not any(k.startswith("$") for k in update_spec.keys()):
        for k, v in update_spec.items():
            result[k] = v
    return result


# ─── Cursor (chainable query result) ────────────────────────────────────

class _Cursor:
    """Chainable cursor mimicking Motor's find cursor.
    Supports .sort(field, direction), .limit(n), .to_list(n)."""

    def __init__(self, coll, filters, projection=None):
        self._coll = coll
        self._filters = filters or {}
        self._projection = projection
        self._sort_field = None
        self._sort_direction = 1
        self._limit = None
        self._or_clauses = None

    def sort(self, field, direction=1):
        if isinstance(field, list):
            # e.g. sort=[("created_at", -1)] — take first for simplicity
            field, direction = field[0]
        self._sort_field = field
        self._sort_direction = direction
        return self

    def limit(self, n):
        self._limit = n
        return self

    def __aiter__(self):
        return _CursorIter(self)

    async def to_list(self, length=None):
        n = length or self._limit or 1000
        docs = await self._fetch(n)
        return docs

    async def _fetch(self, n):
        from google.cloud.firestore_v1 import Query

        def _do_sync():
            # Handle $or by issuing parallel queries and merging
            if "$or" in self._filters:
                or_clauses = self._filters["$or"]
                rest = {k: v for k, v in self._filters.items() if k != "$or"}
                seen_keys = set()
                merged = []
                for clause in or_clauses:
                    combined = {**rest, **clause}
                    q = self._coll._firestore_collection
                    q = _apply_where(q, combined)
                    if self._sort_field:
                        q = q.order_by(
                            self._sort_field,
                            direction=Query.DESCENDING if self._sort_direction == -1 else Query.ASCENDING,
                        )
                    q = q.limit(n)
                    for snap in q.stream():
                        d = snap.to_dict() or {}
                        key = snap.reference.path
                        if key in seen_keys:
                            continue
                        seen_keys.add(key)
                        merged.append(d)
                        if len(merged) >= n:
                            break
                    if len(merged) >= n:
                        break
                return merged

            # Normal path
            q = self._coll._firestore_collection
            q = _apply_where(q, self._filters)
            if self._sort_field:
                q = q.order_by(
                    self._sort_field,
                    direction=Query.DESCENDING if self._sort_direction == -1 else Query.ASCENDING,
                )
            q = q.limit(n)
            return [snap.to_dict() or {} for snap in q.stream()]

        docs = await _run_blocking(_do_sync)
        keep = _drop_id_projection(self._projection)
        return [_apply_projection(d, keep) for d in docs]


class _CursorIter:
    def __init__(self, cursor):
        self._cursor = cursor
        self._buffer = None
        self._idx = 0

    async def __anext__(self):
        if self._buffer is None:
            self._buffer = await self._cursor.to_list(self._cursor._limit or 1000)
        if self._idx >= len(self._buffer):
            raise StopAsyncIteration
        item = self._buffer[self._idx]
        self._idx += 1
        return item


# ─── Collection wrapper ─────────────────────────────────────────────────

class _Collection:
    """Motor-compatible collection wrapper backed by Firestore."""

    def __init__(self, name):
        self.name = name
        self._client = _init_firestore()
        self._firestore_collection = self._client.collection(name)

    def _derive_doc_id(self, doc: dict) -> Optional[str]:
        """Pick a collection-unique document ID from the doc's natural key.

        IMPORTANT: only include fields that are genuinely unique WITHIN a
        collection. `user_id` is a foreign key (many docs per user) and MUST
        NOT be used as the Firestore document ID — doing so overwrites every
        row the user has in that collection.

        The `users` collection is the one exception: there user_id IS the
        primary key by convention. We allow that only for the `users` collection.
        """
        # Collection-specific primary keys (unique within this collection)
        collection_pk = {
            "users": ("user_id", "firebase_uid", "email"),
            "tos_acceptances": ("acceptance_id",),
            "deletion_requests": ("request_id",),
            "documents": ("doc_id",),
            "tracked_cases": ("track_id",),
            "workflow_history": ("gen_id",),
            "query_history": ("history_id",),
            "matters": ("matter_id",),
            "clients": ("client_id",),
            "audit_logs": ("log_id",),
        }
        keys = collection_pk.get(self.name, ())
        for k in keys:
            v = doc.get(k)
            if v:
                return str(v)
        # Fallback: look for any *_id field that's not user_id/matter_id/firm_id/client_id
        # (those are typically foreign keys in other collections)
        FK = {"user_id", "matter_id", "firm_id", "client_id", "firebase_uid"}
        for k, v in doc.items():
            if k.endswith("_id") and k not in FK and v:
                return str(v)
        return None

    async def insert_one(self, doc: dict):
        doc = dict(doc)
        doc.pop("_id", None)
        doc_id = self._derive_doc_id(doc)

        def _do():
            if doc_id:
                self._firestore_collection.document(doc_id).set(doc)
                return type("R", (), {"inserted_id": doc_id})()
            ref = self._firestore_collection.document()
            ref.set(doc)
            return type("R", (), {"inserted_id": ref.id})()

        return await _run_blocking(_do)

    async def find_one(self, filters: Optional[dict] = None, projection: Optional[dict] = None,
                       sort=None):
        filters = filters or {}
        keep = _drop_id_projection(projection)

        def _do():
            from google.cloud.firestore_v1 import Query

            # Handle $or by issuing two queries
            if "$or" in filters:
                or_clauses = filters["$or"]
                rest = {k: v for k, v in filters.items() if k != "$or"}
                for clause in or_clauses:
                    combined = {**rest, **clause}
                    q = self._firestore_collection
                    q = _apply_where(q, combined)
                    q = q.limit(1)
                    for snap in q.stream():
                        return snap.to_dict() or {}
                return None

            q = self._firestore_collection
            q = _apply_where(q, filters)
            if sort:
                if isinstance(sort, list):
                    sf, sd = sort[0]
                else:
                    sf, sd = sort
                q = q.order_by(sf, direction=Query.DESCENDING if sd == -1 else Query.ASCENDING)
            q = q.limit(1)
            for snap in q.stream():
                return snap.to_dict() or {}
            return None

        d = await _run_blocking(_do)
        return _apply_projection(d, keep)

    def find(self, filters: Optional[dict] = None, projection: Optional[dict] = None):
        return _Cursor(self, filters, projection)

    async def update_one(self, filters: dict, update_spec: dict, upsert: bool = False):
        """Update one doc matching filters. If derived doc_id from filters
        matches, we patch directly; otherwise we fetch-first then write."""

        def _do():
            # Fast path: if filters have a known identifier, address directly
            doc_id = None
            for k in ("acceptance_id", "doc_id", "user_id", "track_id", "gen_id"):
                if filters.get(k) and not isinstance(filters[k], dict):
                    doc_id = str(filters[k])
                    break

            if doc_id:
                ref = self._firestore_collection.document(doc_id)
                snap = ref.get()
                if snap.exists:
                    existing = snap.to_dict() or {}
                    new_doc = _apply_update_ops(existing, update_spec)
                    ref.update(update_spec.get("$set", {}) or {k: v for k, v in update_spec.items() if not k.startswith("$")})
                    return type("R", (), {"matched_count": 1, "modified_count": 1, "upserted_id": None})()
                elif upsert:
                    new_doc = _apply_update_ops({}, update_spec)
                    new_doc.update({k: v for k, v in filters.items() if not k.startswith("$") and not isinstance(v, dict)})
                    ref.set(new_doc)
                    return type("R", (), {"matched_count": 0, "modified_count": 0, "upserted_id": doc_id})()
                return type("R", (), {"matched_count": 0, "modified_count": 0, "upserted_id": None})()

            # Slow path: query first
            q = self._firestore_collection
            q = _apply_where(q, filters).limit(1)
            for snap in q.stream():
                existing = snap.to_dict() or {}
                snap.reference.update(update_spec.get("$set", {}) or
                                       {k: v for k, v in update_spec.items() if not k.startswith("$")})
                return type("R", (), {"matched_count": 1, "modified_count": 1, "upserted_id": None})()

            if upsert:
                new_doc = _apply_update_ops({}, update_spec)
                new_doc.update({k: v for k, v in filters.items() if not k.startswith("$") and not isinstance(v, dict)})
                ref = self._firestore_collection.document()
                ref.set(new_doc)
                return type("R", (), {"matched_count": 0, "modified_count": 0, "upserted_id": ref.id})()
            return type("R", (), {"matched_count": 0, "modified_count": 0, "upserted_id": None})()

        return await _run_blocking(_do)

    async def update_many(self, filters: dict, update_spec: dict):
        def _do():
            q = _apply_where(self._firestore_collection, filters)
            count = 0
            set_ops = update_spec.get("$set", {}) or {k: v for k, v in update_spec.items() if not k.startswith("$")}
            for snap in q.stream():
                snap.reference.update(set_ops)
                count += 1
            return type("R", (), {"matched_count": count, "modified_count": count})()

        return await _run_blocking(_do)

    async def delete_one(self, filters: dict):
        def _do():
            q = _apply_where(self._firestore_collection, filters).limit(1)
            for snap in q.stream():
                snap.reference.delete()
                return type("R", (), {"deleted_count": 1})()
            return type("R", (), {"deleted_count": 0})()

        return await _run_blocking(_do)

    async def delete_many(self, filters: dict):
        def _do():
            q = _apply_where(self._firestore_collection, filters)
            count = 0
            for snap in q.stream():
                snap.reference.delete()
                count += 1
            return type("R", (), {"deleted_count": count})()

        return await _run_blocking(_do)

    async def count_documents(self, filters: Optional[dict] = None):
        filters = filters or {}

        def _do():
            q = _apply_where(self._firestore_collection, filters)
            # Firestore has aggregate count; SDK 2.x supports count()
            try:
                return q.count().get()[0][0].value
            except Exception:
                return sum(1 for _ in q.stream())

        return await _run_blocking(_do)

    async def estimated_document_count(self):
        return await self.count_documents({})

    def list_indexes(self):
        # Firestore manages indexes via console; return empty async iter
        async def _gen():
            if False:
                yield None
        return _gen()

    async def create_index(self, spec, **kwargs):
        # Firestore composite indexes are created via console or firestore.indexes.json
        # No-op here; log for visibility
        logger.debug(f"firestore_adapter: create_index ignored (manage in Firestore console): {spec}")
        return None


# ─── Database wrapper ───────────────────────────────────────────────────

class _Database:
    """Exposes collections via attribute access — `db.users`, `db.documents`, etc.
    Mirrors Motor's AsyncIOMotorDatabase API surface."""

    def __init__(self, name="spectr"):
        self.name = name
        self._collections: dict[str, _Collection] = {}

    def __getattr__(self, name: str) -> _Collection:
        if name.startswith("_"):
            raise AttributeError(name)
        if name not in self._collections:
            self._collections[name] = _Collection(name)
        return self._collections[name]

    def __getitem__(self, name: str) -> _Collection:
        return self.__getattr__(name)

    async def command(self, cmd):
        # Health-check ping — Firestore doesn't have command() but we can
        # list projects to verify auth works
        if cmd == "ping":
            try:
                await _run_blocking(lambda: _init_firestore())
                return {"ok": 1}
            except Exception as e:
                raise RuntimeError(f"Firestore ping failed: {e}")
        raise NotImplementedError(f"firestore_adapter command not supported: {cmd}")

    async def list_collection_names(self):
        def _do():
            c = _init_firestore()
            return [coll.id for coll in c.collections()]

        return await _run_blocking(_do)


def get_firestore_db(name: str = "spectr") -> _Database:
    """Factory — call from server.py to get a Motor-compatible db object
    backed by Firestore."""
    return _Database(name)


async def health_check() -> dict:
    try:
        c = _init_firestore()
        # Touch the client to verify auth
        await _run_blocking(lambda: list(c.collections())[:1] if False else None)
        return {"enabled": True, "status": "reachable", "project_id": c.project}
    except Exception as e:
        return {"enabled": False, "status": "unreachable", "error": str(e)[:300]}
