import asyncio
import os
from dotenv import load_dotenv
from pathlib import Path
from motor.motor_asyncio import AsyncIOMotorClient

load_dotenv(Path(__file__).parent / '.env')

mongo_url = os.environ.get('MONGO_URL', "mongodb://localhost:27017")
db_name = os.environ.get('DB_NAME', "associate_db")

OTHER_LAWS_STATUTES = [
    # Companies Act 2013
    {"act_name": "Companies Act, 2013", "section_number": "2(20)", "section_title": "Company definition", "section_text": "Company means a company incorporated under this Act or under any previous company law.", "keywords": ["company", "incorporation", "definition"]},
    {"act_name": "Companies Act, 2013", "section_number": "134", "section_title": "Financial statement, Board's report, etc.", "section_text": "The financial statement, including consolidated financial statement, if any, shall be approved by the Board of Directors before they are signed on behalf of the Board by the chairperson.", "keywords": ["board report", "financial statement", "signature"]},
    {"act_name": "Companies Act, 2013", "section_number": "135", "section_title": "Corporate Social Responsibility", "section_text": "Every company having net worth of rupees five hundred crore or more, or turnover of rupees one thousand crore or more or a net profit of rupees five crore or more shall constitute a CSR Committee.", "keywords": ["CSR", "social responsibility", "committee", "profit"]},
    {"act_name": "Companies Act, 2013", "section_number": "164", "section_title": "Disqualifications for appointment of director", "section_text": "A person shall not be eligible for appointment as a director of a company if he is of unsound mind, undischarged insolvent, convicted of an offence, or has not filed financial statements for three continuous years.", "keywords": ["director", "disqualification", "insolvent", "convicted"]},
    {"act_name": "Companies Act, 2013", "section_number": "167", "section_title": "Vacation of office of director", "section_text": "The office of a director shall become vacant in case he incurs any of the disqualifications specified in section 164, absents himself from all the meetings of the Board of Directors held during a period of twelve months, etc.", "keywords": ["vacation", "director", "absent", "disqualification"]},

    # GST (CGST Act, 2017)
    {"act_name": "Central Goods and Services Tax Act, 2017", "section_number": "7", "section_title": "Scope of supply", "section_text": "Supply includes all forms of supply of goods or services or both such as sale, transfer, barter, exchange, licence, rental, lease or disposal made or agreed to be made for a consideration by a person in the course or furtherance of business.", "keywords": ["supply", "goods", "services", "sale", "business"]},
    {"act_name": "Central Goods and Services Tax Act, 2017", "section_number": "9", "section_title": "Levy and collection", "section_text": "There shall be levied a tax called the central goods and services tax on all intra-State supplies of goods or services or both, except on the supply of alcoholic liquor for human consumption.", "keywords": ["levy", "CGST", "intra-state"]},
    {"act_name": "Central Goods and Services Tax Act, 2017", "section_number": "16", "section_title": "Eligibility and conditions for taking input tax credit", "section_text": "Every registered person shall, subject to such conditions and restrictions as may be prescribed and in the manner specified in section 49, be entitled to take credit of input tax charged on any supply of goods or services or both to him which are used or intended to be used in the course or furtherance of his business.", "keywords": ["ITC", "input tax credit", "registered person", "business"]},
    {"act_name": "Central Goods and Services Tax Act, 2017", "section_number": "73", "section_title": "Determination of tax not paid or short paid or erroneously refunded (Non-fraud)", "section_text": "Where it appears to the proper officer that any tax has not been paid or short paid or erroneously refunded, or where input tax credit has been wrongly availed or utilised for any reason, other than the reason of fraud or any wilful-misstatement or suppression of facts to evade tax, he shall serve notice on the person.", "keywords": ["show cause notice", "SCN", "73", "tax not paid", "no fraud"]},
    {"act_name": "Central Goods and Services Tax Act, 2017", "section_number": "74", "section_title": "Determination of tax not paid or short paid or erroneously refunded (Fraud)", "section_text": "Where it appears to the proper officer that any tax has not been paid or short paid or erroneously refunded or where input tax credit has been wrongly availed or utilised by reason of fraud, or any wilful-misstatement or suppression of facts to evade tax, he shall serve notice on the person.", "keywords": ["show cause notice", "SCN", "74", "fraud", "suppression", "evasion"]},

    # IPC (Indian Penal Code, 1860) / BNS
    {"act_name": "Indian Penal Code, 1860", "section_number": "120B", "section_title": "Punishment of criminal conspiracy", "section_text": "Whoever is a party to a criminal conspiracy to commit an offence punishable with death, imprisonment for life or rigorous imprisonment for a term of two years or upwards, shall be punished in the same manner as if he had abetted such offence.", "keywords": ["criminal conspiracy", "punishment", "abetment"]},
    {"act_name": "Indian Penal Code, 1860", "section_number": "406", "section_title": "Punishment for criminal breach of trust", "section_text": "Whoever commits criminal breach of trust shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.", "keywords": ["breach of trust", "CBT", "punishment", "imprisonment"]},
    {"act_name": "Indian Penal Code, 1860", "section_number": "415", "section_title": "Cheating", "section_text": "Whoever, by deceiving any person, fraudulently or dishonestly induces the person so deceived to deliver any property to any person, or to consent that any person shall retain any property, or intentionally induces the person so deceived to do or omit to do anything which he would not do or omit if he were not so deceived, and which act or omission causes or is likely to cause damage or harm to that person in body, mind, reputation or property, is said to 'cheat'.", "keywords": ["cheating", "deceiving", "fraudulently", "dishonestly"]},
    {"act_name": "Indian Penal Code, 1860", "section_number": "420", "section_title": "Cheating and dishonestly inducing delivery of property", "section_text": "Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, or anything which is signed or sealed, and which is capable of being converted into a valuable security, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.", "keywords": ["cheating", "delivery of property", "valuable security", "420", "seven years"]},
    {"act_name": "Indian Penal Code, 1860", "section_number": "467", "section_title": "Forgery of valuable security, will, etc.", "section_text": "Whoever forges a document which purports to be a valuable security or a will, or an authority to adopt a son, or which purports to give authority to any person to make or transfer any valuable security, or to receive the principal, interest or dividends thereon, or to receive or deliver any money, movable property, or valuable security, or any document purporting to be an acquittance or receipt acknowledging the payment of money, or an acquittance or receipt for the delivery of any movable property or valuable security, shall be punished with imprisonment for life, or with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.", "keywords": ["forgery", "valuable security", "will", "life imprisonment"]},
    {"act_name": "Indian Penal Code, 1860", "section_number": "468", "section_title": "Forgery for purpose of cheating", "section_text": "Whoever commits forgery, intending that the document or electronic record forged shall be used for the purpose of cheating, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.", "keywords": ["forgery", "cheating", "seven years"]},
    {"act_name": "Indian Penal Code, 1860", "section_number": "498A", "section_title": "Husband or relative of husband of a woman subjecting her to cruelty", "section_text": "Whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty shall be punished with imprisonment for a term which may extend to three years and shall also be liable to fine. Explanation: 'cruelty' means any wilful conduct which is of such a nature as is likely to drive the woman to commit suicide or to cause grave injury or danger to life, limb or health (whether mental or physical) of the woman; or harassment of the woman where such harassment is with a view to coercing her or any person related to her to meet any unlawful demand for any property or valuable security or is on account of failure by her or any person related to her to meet such demand.", "keywords": ["cruelty", "husband", "relative", "harassment", "dowry"]},

    # CrPC (Code of Criminal Procedure, 1973)
    {"act_name": "Code of Criminal Procedure, 1973", "section_number": "154", "section_title": "Information in cognizable cases", "section_text": "Every information relating to the commission of a cognizable offence, if given orally to an officer in charge of a police station, shall be reduced to writing by him or under his direction, and be read over to the informant; and every such information, whether given in writing or reduced to writing as aforesaid, shall be signed by the person giving it, and the substance thereof shall be entered in a book to be kept by such officer in such form as the State Government may prescribe in this behalf.", "keywords": ["FIR", "cognizable offence", "police station", "154"]},
    {"act_name": "Code of Criminal Procedure, 1973", "section_number": "156(3)", "section_title": "Police officer's power to investigate cognizable case", "section_text": "Any Magistrate empowered under section 190 may order such an investigation as above-mentioned (investigation of a cognizable case without the order of a Magistrate).", "keywords": ["investigation", "magistrate order", "156(3)"]},
    {"act_name": "Code of Criminal Procedure, 1973", "section_number": "161", "section_title": "Examination of witnesses by police", "section_text": "Any police officer making an investigation under this Chapter, or any police officer not below such rank as the State Government may, by general or special order, prescribe in this behalf, acting on the requisition of such officer, may examine orally any person supposed to be acquainted with the facts and circumstances of the case.", "keywords": ["statement", "witness", "police investigation", "161"]},
    {"act_name": "Code of Criminal Procedure, 1973", "section_number": "164", "section_title": "Recording of confessions and statements", "section_text": "Any Metropolitan Magistrate or Judicial Magistrate may, whether or not he has jurisdiction in the case, record any confession or statement made to him in the course of an investigation under this Chapter or under any other law for the time being in force, or at any time afterwards before the commencement of the inquiry or trial.", "keywords": ["confession", "magistrate", "statement", "164"]},
    {"act_name": "Code of Criminal Procedure, 1973", "section_number": "438", "section_title": "Direction for grant of bail to person apprehending arrest (Anticipatory Bail)", "section_text": "Where any person has reason to believe that he may be arrested on accusation of having committed a non-bailable offence, he may apply to the High Court or the Court of Session for a direction under this section that in the event of such arrest he shall be released on bail; and that Court may, after taking into consideration, inter alia, the following factors, namely: (i) the nature and gravity of the accusation; (ii) the antecedents of the applicant including the fact as to whether he has previously undergone imprisonment on conviction by a Court in respect of any cognizable offence; (iii) the possibility of the applicant to flee from justice; and (iv) where the accusation has been made with the object of injuring or humiliating the applicant by having him so arrested, either reject the application forthwith or issue an interim order for the grant of anticipatory bail.", "keywords": ["anticipatory bail", "438", "apprehending arrest", "non-bailable"]},
    {"act_name": "Code of Criminal Procedure, 1973", "section_number": "439", "section_title": "Special powers of High Court or Court of Session regarding bail", "section_text": "A High Court or Court of Session may direct (a) that any person accused of an offence and in custody be released on bail, and if the offence is of the nature specified in sub-section (3) of section 437, may impose any condition which it considers necessary for the purposes mentioned in that sub-section; (b) that any condition imposed by a Magistrate when releasing any person on bail be set aside or modified.", "keywords": ["regular bail", "custody", "high court", "sessions court", "439"]},

    # NI Act
    {"act_name": "Negotiable Instruments Act, 1881", "section_number": "138", "section_title": "Dishonour of cheque for insufficiency, etc., of funds in the account", "section_text": "Where any cheque drawn by a person on an account maintained by him with a banker for payment of any amount of money to another person from out of that account for the discharge, in whole or in part, of any debt or other liability, is returned by the bank unpaid, either because of the amount of money standing to the credit of that account is insufficient to honour the cheque or that it exceeds the amount arranged to be paid from that account by an agreement made with that bank, such person shall be deemed to have committed an offence and shall, without prejudice to any other provisions of this Act, be punished with imprisonment for a term which may be extended to two years, or with fine which may extend to twice the amount of the cheque, or with both.", "keywords": ["cheque bounce", "dishonour", "138", "insufficient funds", "two years", "twice amount"]},
    {"act_name": "Negotiable Instruments Act, 1881", "section_number": "141", "section_title": "Offences by companies", "section_text": "If the person committing an offence under section 138 is a company, every person who, at the time the offence was committed, was in charge of, and was responsible to the company for the conduct of the business of the company, as well as the company, shall be deemed to be guilty of the offence and shall be liable to be proceeded against and punished accordingly.", "keywords": ["directors liability", "company offence", "141"]},

    # PMLA (Prevention of Money-Laundering Act, 2002)
    {"act_name": "Prevention of Money-Laundering Act, 2002", "section_number": "3", "section_title": "Offence of money-laundering", "section_text": "Whosoever directly or indirectly attempts to indulge or knowingly assists or knowingly is a party or is actually involved in any process or activity connected with the proceeds of crime including its concealment, possession, acquisition or use and projecting or claiming it as untainted property shall be guilty of offence of money-laundering.", "keywords": ["money laundering", "proceeds of crime", "untainted property"]},
    {"act_name": "Prevention of Money-Laundering Act, 2002", "section_number": "4", "section_title": "Punishment for money-laundering", "section_text": "Whoever commits the offence of money-laundering shall be punishable with rigorous imprisonment for a term which shall not be less than three years but which may extend to seven years and shall also be liable to fine. Provided that where the proceeds of crime involved in money-laundering relates to any offence specified under paragraph 2 of Part A of the Schedule (NDPS Act offences), the provisions of this section shall have effect as if for the words 'seven years', the words 'ten years' had been substituted.", "keywords": ["punishment", "imprisonment", "fine", "ten years"]},

    # FEMA (Foreign Exchange Management Act, 1999)
    {"act_name": "Foreign Exchange Management Act, 1999", "section_number": "3", "section_title": "Dealing in foreign exchange, etc.", "section_text": "Save as otherwise provided in this Act, rules or regulations made thereunder, or with the general or special permission of the Reserve Bank, no person shall (a) deal in or transfer any foreign exchange or foreign security to any person not being an authorised person; (b) make any payment to or for the credit of any person resident outside India in any manner; (c) receive otherwise through an authorised person, any payment by order or on behalf of any person resident outside India in any manner. Explanation: For the purpose of this clause, where any person in, or resident in, India receives any payment by order or on behalf of any person resident outside India through any other person (including an authorised person) without a corresponding inward remittance from any place outside India, then, such person shall be deemed to have received such payment otherwise than through an authorised person; (d) enter into any financial transaction in India as consideration for or in association with acquisition or creation or transfer of a right to acquire, any asset outside India by any person.", "keywords": ["foreign exchange", "authorized person", "remittance", "FEMA", "violation"]}
]

async def seed_other():
    client = AsyncIOMotorClient(mongo_url)
    database = client[db_name]
    
    # Check if already seeded to prevent duplication
    existing = await database.statutes.find_one({"act_name": "Companies Act, 2013", "section_number": "2(20)"})
    if existing:
        print("Other Laws statutes already seeded. Skipping.")
        client.close()
        return
    
    print(f"Seeding {len(OTHER_LAWS_STATUTES)} sections from major Indian Laws...")
    await database.statutes.insert_many(OTHER_LAWS_STATUTES)
    
    # Create indexes
    await database.statutes.create_index([("act_name", 1), ("section_number", 1)])
    await database.statutes.create_index([("keywords", 1)])
    await database.statutes.create_index([
        ("section_text", "text"),
        ("section_title", "text"),
        ("act_name", "text")
    ])
    
    print(f"Successfully seeded {len(OTHER_LAWS_STATUTES)} entries for Other Major Laws.")
    client.close()

if __name__ == "__main__":
    asyncio.run(seed_other())
