#!/usr/bin/env bash
# new-firm.sh <shortname> "<Firm Full Name>" — provisions new dedicated firm instance
#
# Usage:
#   ./scripts/new-firm.sh cam "Cyril Amarchand Mangaldas"
#   ./scripts/new-firm.sh sam "Shardul Amarchand Mangaldas"
#
# What it does (15-min automated setup):
#   1. Creates firms/<shortname>/ directory with templates
#   2. Creates Fly.io app: <shortname>-spectr
#   3. Provisions MongoDB Atlas cluster (or uses existing)
#   4. Sets up Cloudflare DNS: <shortname>.spectr.in → Fly app
#   5. Reminds you to create Google OAuth client + add secrets
#   6. Does initial deploy
#
# Requires: flyctl, curl, jq, gh (optional for repo setup)

set -euo pipefail

SHORT="${1:-}"
FULL_NAME="${2:-}"
if [ -z "$SHORT" ] || [ -z "$FULL_NAME" ]; then
    echo "Usage: $0 <shortname> \"<Firm Full Name>\""
    echo "Example: $0 cam \"Cyril Amarchand Mangaldas\""
    exit 1
fi

# Validate shortname (DNS-safe)
if [[ ! "$SHORT" =~ ^[a-z][a-z0-9-]{1,30}$ ]]; then
    echo "Shortname must be lowercase, start with letter, 2-31 chars, only a-z 0-9 -"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$REPO_ROOT"

APP_NAME="${SHORT}-spectr"
SUBDOMAIN="${SHORT}.spectr.in"
FIRM_DIR="firms/$SHORT"

echo "╔════════════════════════════════════════════════════╗"
echo "║  New Firm Provisioning"
echo "║  Shortname: $SHORT"
echo "║  Full name: $FULL_NAME"
echo "║  App:       $APP_NAME"
echo "║  Subdomain: $SUBDOMAIN"
echo "╚════════════════════════════════════════════════════╝"

# 1. Create firms/<short>/ directory
if [ -d "$FIRM_DIR" ]; then
    echo "⚠  Firm directory $FIRM_DIR already exists. Skipping creation."
else
    echo
    echo "[1/6] Creating firm directory..."
    mkdir -p "$FIRM_DIR"

    cat > "$FIRM_DIR/config.json" <<EOF
{
  "mode": "dedicated",
  "firm_name": "$FULL_NAME",
  "limits": {
    "max_queries_per_day": 10000,
    "max_files_upload": 15,
    "max_file_size_mb": 200,
    "max_deep_research_per_day": 500,
    "max_drive_uploads_per_day": 2000,
    "sandbox_minutes_per_day": 2000,
    "concurrent_sandboxes": 5
  },
  "features": {
    "advisory": true,
    "code_executor": true,
    "deep_research": true,
    "drive_upload": true,
    "sheets_live_edit": true,
    "docs_live_edit": true,
    "vault": true,
    "playbooks": true,
    "trust_layer": true,
    "multi_tenant_signup": false,
    "billing": false,
    "admin_dashboard": true
  }
}
EOF

    cat > "$FIRM_DIR/branding.json" <<EOF
{
  "app_name": "Spectr — $FULL_NAME",
  "firm_name": "$FULL_NAME",
  "tagline": "Internal AI Legal Intelligence",
  "primary_color": "#0A0A0A",
  "accent_color": "#D4AF37",
  "bg_color": "#FAFAFA",
  "logo_url": "/static/$SHORT-logo.svg",
  "font_heading": "Plus Jakarta Sans",
  "font_body": "Inter",
  "email_from": "ai@$SHORT.com",
  "email_footer": "— $FULL_NAME | Powered by Spectr"
}
EOF

    cat > "$FIRM_DIR/prompt_override.md" <<EOF
# DEPLOYMENT — $FULL_NAME

You are running on the **$FULL_NAME** dedicated Spectr instance.

## Drafting conventions

- Use $FULL_NAME's standard letterhead and citation style.
- Match the formal tone expected by $FULL_NAME partners.
- Reference internal templates when drafting contracts (via Vault).

## Behaviors

- All users on this instance are $FULL_NAME team members.
- Do not reference generic SaaS disclaimers — this is a dedicated deployment.
EOF

    cat > "$FIRM_DIR/disclaimer.md" <<EOF
**CONFIDENTIAL** — This analysis is generated by $FULL_NAME's internal AI (powered by Spectr). It is work product intended solely for $FULL_NAME attorneys and staff. All citations, calculations, and deadlines must be independently verified before filing or client delivery.
EOF

    echo "✓ Created $FIRM_DIR/"
fi

# 2. Create Fly.io app
echo
echo "[2/6] Creating Fly.io app '$APP_NAME'..."
if flyctl apps list 2>/dev/null | grep -q "$APP_NAME"; then
    echo "  App already exists, skipping."
else
    cat > "/tmp/fly-${SHORT}.toml" <<EOF
app = "$APP_NAME"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[env]
  FIRM_SHORT = "$SHORT"
  PORT = "8000"
  WORKERS = "2"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = "shared-cpu-2x"
  memory = "2gb"
EOF
    flyctl launch --config "/tmp/fly-${SHORT}.toml" --name "$APP_NAME" --region bom --no-deploy --copy-config 2>&1 || echo "  Note: launch may have partial success"
    echo "✓ Fly app '$APP_NAME' created"
fi

# 3. MongoDB (manual for now)
echo
echo "[3/6] MongoDB setup"
echo "  ⚠ MANUAL STEP: Provision a dedicated MongoDB Atlas cluster for $FULL_NAME."
echo "    → https://cloud.mongodb.com/v2/dashboard"
echo "    → Create cluster '${SHORT}-spectr-db'"
echo "    → Whitelist Fly.io IPs: 0.0.0.0/0 (or specific Fly ranges)"
echo "    → Create user + password"
echo "    → Copy connection string"
echo "    → Run: flyctl secrets set MONGO_URL='mongodb+srv://...' --app $APP_NAME"

# 4. Cloudflare DNS (manual for now)
echo
echo "[4/6] Cloudflare DNS"
echo "  ⚠ MANUAL STEP: Add DNS record:"
echo "    Type:    CNAME"
echo "    Name:    $SHORT"
echo "    Target:  $APP_NAME.fly.dev"
echo "    Proxied: Yes"
echo "  Then:  flyctl certs create $SUBDOMAIN --app $APP_NAME"

# 5. Google OAuth
echo
echo "[5/6] Google OAuth setup"
echo "  ⚠ MANUAL STEP: Create dedicated OAuth client for $FULL_NAME"
echo "    → https://console.cloud.google.com/apis/credentials"
echo "    → Create OAuth 2.0 Client ID (Web application)"
echo "    → Authorized redirect URI: https://$SUBDOMAIN/api/google/auth/callback"
echo "    → Enable: Drive API, Sheets API, Docs API"
echo "    → Run:"
echo "      flyctl secrets set \\"
echo "        GOOGLE_OAUTH_CLIENT_ID=<client_id> \\"
echo "        GOOGLE_OAUTH_CLIENT_SECRET=<client_secret> \\"
echo "        GOOGLE_OAUTH_REDIRECT_URI=https://$SUBDOMAIN/api/google/auth/callback \\"
echo "        --app $APP_NAME"

# 6. Remaining secrets
echo
echo "[6/6] Remaining secrets to set (copy-paste these):"
echo
cat <<EOF
flyctl secrets set --app $APP_NAME \\
    MONGO_URL="mongodb+srv://USER:PASS@...mongodb.net/$SHORT_db" \\
    GOOGLE_OAUTH_CLIENT_ID="xxx.apps.googleusercontent.com" \\
    GOOGLE_OAUTH_CLIENT_SECRET="GOCSPX-xxx" \\
    GOOGLE_OAUTH_REDIRECT_URI="https://$SUBDOMAIN/api/google/auth/callback" \\
    GROQ_KEY="gsk_..." \\
    GOOGLE_AI_KEY="AIza..." \\
    OPENAI_KEY="sk-proj-..." \\
    ANTHROPIC_API_KEY="sk-ant-..." \\
    BL_API_KEY="..." \\
    INDIANKANOON_API_KEY="..." \\
    SERPER_API_KEY="..." \\
    AGENTMAIL_API_KEY="..." \\
    FIRM_SHORT="$SHORT"
EOF

echo
echo "After secrets are set, run:"
echo "  ./scripts/deploy.sh $SHORT"
echo
echo "Once deployed, verify:"
echo "  curl https://$SUBDOMAIN/health"
echo
echo "╔════════════════════════════════════════════════════╗"
echo "║  Provisioning complete. Remember to commit:"
echo "║    git add $FIRM_DIR"
echo "║    git commit -m \"Add firm: $FULL_NAME\""
echo "╚════════════════════════════════════════════════════╝"
